// components/Layout.tsx
import { Navbar } from '~/components/Navbar';
import { Footer } from '~/components/Footer';
import { BackToTop } from '~/components/BackToTop';

export function Layout({ children }) {
  return (
    <div className="bg-white dark:bg-neutral-900 ">
      <BackToTop />
      <Navbar />
      <div className="container mx-auto pt-10 lg:pt-2 w-full font-sans print:pt-0">
        <main className="flex flex-col pt-16 px-8 sm:px-16 md:px-32 lg:px-40 xl:px-56 2xl:px-72 print:pt-0">
          <div className="flex-1 h-full min-h-screen">{children}</div>
          <Footer />
        </main>
      </div>
    </div>
  );
}

// src/routes/__layout.svelte
<script lang="ts">
  import Navbar from '../../src/components/navbar.svelte';
  import 'virtual:windi.css';
</script>

<div
  class="font-body bg-gradient-to-r from-rose-100 to-teal-100 text-black dark:(bg-gradient-to-r from-gray-700 via-gray-900 to-black text-light-100) min-h-screen h-full w-full"
>
  <div class="container mx-auto lg:px-48 md:px-32 sm:px-20 px-8 py-8">
    <Navbar />
    <slot />
  </div>
</div>

<style>
  @import '@fontsource/manrope';
</style>
